### ISSUE TITLE
[BUG] Docs omit length-1 limitation on alphabet symbols

### ISSUE THREAD

**Issue by jasonhemann** [morazanm/fsm#15]
**Describe the bug**

Docs don't explicitly state that alphabet symbols are limited to symbols with a string representation of length 1. The error messages associated with that failure don't mention this problem either.

**To Reproduce**
```
> (make-ndfa (list 'A) (list 'abc) 'A (list) (list))

 ALPHABET ERRORS for: (abc)
    These are non-alphabetic or uppercase in your "alphabet" (abc)
; Check above message for error
; Context (errortrace):
;    test.rkt:56:0: (make-ndfa (list (quote A)) (list (quote abc)) (quote A) (list) (list))
```

**Comment by jasonhemann** [comment]
Documentation is overly restrictive in another sense, in that the ndfa constructor permits Racket numbers as symbols in the alphabet.

```
> (make-ndfa (list 'A) (list 12 34 1234) 'A (list) (list))
#<procedure:....2/pkgs/fsm/fsa.rkt:70:6>
```

**Comment by jasonhemann** [comment]
Upon reflection, it seems like the [numbers issue](https://github.com/morazanm/fsm/issues/15#issuecomment-965625167) is an overly-permissive implementation rather than a bug in documentation. For instance, while `fsm` permits numbers as alphabet symbols, other parts of the package aren't equipped to handle them.

```
> (make-cfg (list 'A 'B 'C) (list '123 '1 '2 '3) (list) 'A)
(cfg '(A B C) '(123 1 2 3) '() 'A)
> (make-cfg (list 'A 'B 'C) (list '1 '12 '2 '3 '23) (list (list 'A ARROW '123)) 'A)
; symbol->string: contract violation
;   expected: symbol?
;   given: 123
```

I don't know whether or not `fsm` should permit single-digit numbers as symbols in the alphabet. However, permitting numbers of two or more digits seems like it's asking for trouble.

**Comment by morazanm** [comment]
Documentation updated in commit 0142c9c7db9135608ec1e96f93996b2d812b3b78.
