### ISSUE TITLE
[BUG] Documentation error; `grammar-rename-nts` omits a parameter 

### ISSUE THREAD

**Issue by jasonhemann** [morazanm/fsm#16]
**Describe the bug**
Currently, the documentation available [here]() omits the first parameter of `grammar-rename-nts`, the variables to rename away from, and following the documented behavior signals an error.

```
(grammar-rename-nts g) → grammar
```

I imagine should be 

```
(grammar-rename-nts (listof nts) g) → grammar
```

**Comment by morazanm** [comment]
Fixed in commit 68efeec9a9a58f336fcc2e82960430ec72aaf362.
