### ISSUE TITLE
[BUG] Manual oughta display optional args as optional, a la Racket docs

### ISSUE THREAD

**Issue by jasonhemann** [morazanm/fsm#18]
Right now in several places optional arguments are listed as though they're mandatory; that they're optional only appears in the prose. Examples include `grammar-testequiv` and `grammar-test`. Cf., e.g., [range](https://docs.racket-lang.org/reference/pairs.html#%28def._%28%28lib._racket%2Flist..rkt%29._range%29%29).

**Comment by morazanm** [comment]
Documentation updated to better reflect optional arguments in b115bd483458df6009acdd18147120cb91604d60 .
