### ISSUE TITLE
[BUG] Repository missing file `./FSM-Visualization/graphViz/hello_world.png`

### ISSUE THREAD

**Issue by jasonhemann** [morazanm/fsm#19]
Currently, testing the file `./FSM-Visualization/graphViz/shell.rkt` fails because `./FSM-Visualization/graphViz/hello_world.png` is missing. I believe this file needs to be checked in to the repository.

**Comment by jschappel** [comment]
This was a leftover file from the original Graph-viz implementation. After running a grep of the filesystem its not used anywhere so I removed the file in 0636bbf
