### ISSUE TITLE
[BUG] `cfg-star` is implemented but not provided, no `grammar-star` op available

### ISSUE THREAD

**Issue by jasonhemann** [morazanm/fsm#22]
**Describe the bug**

I see that `cfg-star` exists in `cfg.rkt` but it is not provided out. I think it should be provided up several layers to an external-facing `grammar-star` operation.

**Comment by morazanm** [comment]
grammar-kleenestar added to FSM. This works for regular and context-free grammars. Still pending: kleenestar of a context-sensitive grammar. Addition done in: 6c28761218bcc2e14b0aa1c4f35d0eee6277d1f0
