### ISSUE TITLE
[Question] What are the additional `rest` args in `make-ndpda` ? 

### ISSUE THREAD

**Issue by jasonhemann** [morazanm/fsm#23]
I see from the [definition of `make-ndpda`](https://github.com/morazanm/fsm/blob/e82dc0bbf98d26e14edf90ee50548298c84ea90e/fsm-main.rkt#L358)

that it permits additional arguments beyond the expected tuple. Why is that permitted, and what are those for? [`make-unchecked-ndpda`](https://github.com/morazanm/fsm/blob/e82dc0bbf98d26e14edf90ee50548298c84ea90e/pda.rkt#L109) doesn't seem prepared to accept those additional arguments, but maybe I'm missing something.

**Comment by morazanm** [comment]
This is simply work in progress for the eventual deployment of make-dpda for deterministic pda. The extra argument will be a flag for adding a dead state and missing transitions to the constructed machine.
