### ISSUE TITLE
`big-length-error` can print without appropriate newlines under some error conditions

### ISSUE THREAD

**Issue by jasonhemann** [morazanm/fsm#24]
The [`big-length-error`](https://github.com/morazanm/fsm/blob/e82dc0bbf98d26e14edf90ee50548298c84ea90e/abstract-predicate.rkt#L342-L353) seems to presume, at least in the output printing format, that there will be length errors whenever there are final-state errors, which is not always the case. For a PDA like the following

```
(make-ndpda '(a b c) '(d e f) '(d e f x) 'a 'b '())
```

I receive the corresponding output at the REPL, note that `b` abuts the procedure:

```
The given list of final states is not a list: b#<procedure:...cuments/fsm/pda.rkt:160:4>
test-fsm.rkt> 
```

**Comment by morazanm** [comment]
The error message is correct. 'b is not a list of final states.

The abutting has been fixed.
