### ISSUE TITLE
[BUG] Incorrect symbol casing bleeds through to host lang level error message

### ISSUE THREAD

**Issue by jasonhemann** [morazanm/fsm#27]
This seems related to you all's TFPIE '18 paper on error messages. 

In a malformed pda like `(make-ndpda '(a) '(d) '(d) 'a '(a) '())`, we end up seeing that mistake presented as a substring error, rather than something expressed at the level of the automaton itself.

```
; substring: ending index is out of range
;   ending index: 2
;   valid range: [0, 1]
;   string: "a"
; Context (errortrace):
...
```

**Comment by morazanm** [comment]
Bug in testing a list of states fixed. Testing for 'ds failed to make sure length of equivalent string is 2 causing a string ref out of bounds error.
