### ISSUE TITLE
[BUG] `convert-to-cnf` will loop infinitely on a grammar with self-loops

### ISSUE THREAD

**Issue by jasonhemann** [morazanm/fsm#28]
**Describe the bug**

On two nearly-identical grammars, the only difference an additional rule `(D -> D)`, `convert-to-cnf` of the former finitely terminates and the latter goes into an infinite loop.  See examples below. This matters more because `grammar-testequiv` depends on `grammar-derive`, which in this instance depends on `cfg-derive` which in turn depends on `convert-to-cnf`.

```
(convert-to-cnf (make-cfg
                          '(A C B D)
                          '(a b)
                          (list
                           (list 'D '-> 'a)
                           (list 'B '-> 'b)
                           (list 'C '-> 'B)
                           (list 'D '-> 'CD)
                           (list 'D '-> 'aB)
                           (list 'D '-> 'CDC)
                           (list 'A '-> 'D)
                           (list 'C '-> 'D)
                           (list 'D '-> 'DC))
                          'A))
```

```
(convert-to-cnf (make-cfg
                          '(A C B D)
                          '(a b)
                          (list
                           (list 'D '-> 'a)
                           (list 'B '-> 'b)
                           (list 'C '-> 'B)
                           (list 'D '-> 'CD)
                           (list 'D '-> 'aB)
                           (list 'D '-> 'CDC)
                           (list 'D '-> 'D) ;; See this addition
                           (list 'A '-> 'D)
                           (list 'C '-> 'D)
                           (list 'D '-> 'DC))
                          'A))
```

**Comment by morazanm** [comment]
A previous fix to convert-to-cnf has resolved this issue. The example in the bug report now:

> (convert-to-cnf (make-cfg
                          '(A C B D)
                          '(a b)
                          (list
                           (list 'D '-> 'a)
                           (list 'B '-> 'b)
                           (list 'C '-> 'B)
                           (list 'D '-> 'CD)
                           (list 'D '-> 'aB)
                           (list 'D '-> 'CDC)
                           (list 'D '-> 'D) ;; See this addition
                           (list 'A '-> 'D)
                           (list 'C '-> 'D)
                           (list 'D '-> 'DC))
                          'A))
(cfg
 '(B A-3981080 T-3981082 D C A-3981079)
 '(a b)
 (list
  (cfg-rule 'D '(a))
  (cfg-rule 'B '(b))
  (cfg-rule 'D '(C D))
  (cfg-rule 'D '(A-3981080 B))
  (cfg-rule 'D '(D C))
  (cfg-rule 'A-3981080 '(a))
  (cfg-rule 'D '(C T-3981082))
  (cfg-rule 'T-3981082 '(D C))
  (cfg-rule 'C '(b))
  (cfg-rule 'D '(a))
  (cfg-rule 'D '(C D))
  (cfg-rule 'D '(A-3981080 B))
  (cfg-rule 'D '(D C))
  (cfg-rule 'D '(C T-3981082))
  (cfg-rule 'C '(a))
  (cfg-rule 'C '(C D))
  (cfg-rule 'C '(A-3981080 B))
  (cfg-rule 'C '(D C))
  (cfg-rule 'C '(C T-3981082))
  (cfg-rule 'C '(a))
  (cfg-rule 'C '(C D))
  (cfg-rule 'C '(A-3981080 B))
  (cfg-rule 'C '(D C))
  (cfg-rule 'C '(C T-3981082))
  (cfg-rule 'A-3981079 '(a))
  (cfg-rule 'A-3981079 '(C D))
  (cfg-rule 'A-3981079 '(A-3981080 B))
  (cfg-rule 'A-3981079 '(D C))
  (cfg-rule 'A-3981079 '(C T-3981082))
  (cfg-rule 'A-3981079 '(a))
  (cfg-rule 'A-3981079 '(C D))
  (cfg-rule 'A-3981079 '(A-3981080 B))
  (cfg-rule 'A-3981079 '(D C))
  (cfg-rule 'A-3981079 '(C T-3981082)))
 'A-3981079)
