### ISSUE TITLE
running a tm crashes when given empty string

### ISSUE THREAD

**Issue by stchang** [morazanm/fsm#45]
## Describe the bug
running a tm crashes when given empty string

## Steps to Reproduce
The following program

```racket
#lang racket

(require fsm)

; example from README

; write "a" on tape
(define Ma (make-tm '(S H)                  ;the states
                    `(a b ,LM)              ;the alphabet
                    `(((S ,LM) (S ,RIGHT))  ;the transition relation
                      ((S a) (H a))
                      ((S b) (H a))
                      ((S ,BLANK) (H a)))
                    'S                      ;the starting state
                    '(H)))                  ;the halting states

(sm-apply Ma null)
```

crashes with error: 
```
list-ref: index too large for list
  index: 0
  in: '()
```

## Expected Behavior
should return `'(Halt: H)` state or "didnt reach halt state" msg

## OS Observed On
Linux 5.15.0-48-generic #54~20.04.1-Ubuntu SMP Thu Sep 1 16:17:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal

**Comment by morazanm** [comment]
This is a misuse, not a bug. A Turing machine cannot be empty. It must at least have the left end marker on it. The sample Turing machine in the provided example ought to be used as follows:

> (sm-apply Ma `(,LM))
'(Halt: H)
> (sm-showtransitions Ma `(,LM))
'((S 0 (@)) (S 1 (@ _)) (H 1 (@ a)))

**Comment by stchang** [comment]
Thanks for the clarification. But should the library give a more informative message about the misuse?

**Comment by morazanm** [comment]
Yes, it should. It's on my pile now. :-)

Marco

**Comment by stchang** [comment]
I'll submit a fix
