### ISSUE TITLE
bug: #62 does not run; ("rkt.dot" - no such file or directory)

### ISSUE THREAD

**Issue by oliwial23** [morazanm/fsm#63]
## Describe the bug
Following the fix from #62 the code still does not run. The problem seems to be with the "dot.rkt" file. The error message mentions there is "no such file or directory."

## Steps to Reproduce
1) Run:
(require 2htdp/image "dot.rkt")

## Expected Behavior
Expecting code #62 to run.

## OS Observed On
macOS Ventura 13.1

## Screenshots
<img width="1440" alt="Bildschirm­foto 2023-02-16 um 12 32 34" src="https://user-images.githubusercontent.com/119520637/219444113-58dec583-e67a-468e-a4e4-a71a0185f7b4.png">

**Comment by jschappel** [comment]
Is `dot.rkt` saved within the same folder as `MarcoBug.rkt`?
