### ISSUE TITLE
ndfa->regexp unbound identifier

### ISSUE THREAD

**Issue by ajay340** [morazanm/fsm#7]
The documentation outlines the function ndfa->regexp which takes as input an ndfa machine and returns a regexp. However, calling on the function returns an error "ndfa->regexp: unbound identifier in: ndfa->regexp" despite the fsm library being imported.

**Comment by morazanm** [comment]
That is a typo in the documentation. The correct function is: fsa->regexp . Be careful with this function, because it can quickly make DrRacket run out of memory.

**Comment by jschappel** [comment]
We should make sure to update the documentation. I am reopening this issue till it is resolved. We should also inform the user that memory can become an issue.

**Comment by sachinmahashabde** [comment]
Error was fixed in the documentation. Thank you for pointing this out Ajay.
