### ISSUE TITLE
Docs: Ambiguity in pda docs

### ISSUE THREAD

**Issue by jschappel** [morazanm/fsm#70]
There are spelling errors in the description of [(make-ndpda)](https://morazanm.github.io/fsm/fsm/State_Machine_Constructors.html#%28def._%28%28lib._fsm%2Fmain..rkt%29._make-ndpda%29%29). 
> of stack symbols, statr state

Also the stack alphabet just says that it is a `listof(symbol)` should this be more restricted like the [alphabet](https://morazanm.github.io/fsm/fsm/Data_Definitions.html#%28form._%28%28lib._fsm%2Fmain..rkt%29._alphabet%29%29) is?

**Comment by morazanm** [comment]
Fixed typo. The stack alphabet is not restricted like the input alphabet.
