### ISSUE TITLE
[Documentation Issue] regexp->ndfa unbound identifier

### ISSUE THREAD

**Issue by ajay340** [morazanm/fsm#8]
The documentation outlines the function regexp->ndfa which takes as input a regexp and returns a ndfa. However, calling on the function returns an error "regexp->ndfa: unbound identifier in: ndfa->regexp" despite the fsm library being imported.

**Comment by jschappel** [comment]
After looking into this Sach has fixed it in tomorrows update. Please use fsa->regexp since that is the proper function.

**Comment by jschappel** [comment]
Documentation has been updated. Closing issue
